import{a as d,S as y,i as c}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function g(a){return a.map(({id:t,webformatURL:s,largeImageURL:o,views:e,likes:r,comments:n,downloads:f,tags:m})=>`
      <a href="${o}" class="card">
         <img class="card__img" src="${s}" alt="${m}" />
         <div class="card__info">
           <p class="card__numbers"><span>Views:</span> ${e}</p>
           <p class="card__numbers"><span>Likes:</span> ${r}</p>
           <p class="card__numbers"><span>Comments:</span> ${n}</p>
           <p class="card__numbers"><span>Downloads:</span> ${f}</p>
         </div>
      </a>
      `).join("")}const h="https://pixabay.com",_="/api/",b="15968525-5a53092c6d62a7b9e458a529a";async function L(a){const t=new URLSearchParams({key:b,image_type:"photo",safesearch:!0,orientation:"horizontal",q:a}).toString(),s={Accept:"application/json","Content-Type":"application/json","Referrer-Policy":"no-referrer","X-Requested-With":"XMLHttpRequest"},o=`${h}${_}?${t}`;try{return(await d.get(o,s)).data}catch(e){e.response?iziToast.error({title:"Error",message:`HTTP error! status: ${e.response.status} - ${e.response.statusText}`}):iziToast.error({title:"Error",message:e.message});return}}const p=document.querySelector(".form"),i=document.querySelector(".gallery"),S=new y(".gallery a"),l=document.querySelector(".loader"),u=document.querySelector(".loader__overlay"),$=a=>{a.preventDefault(),l.style.display="block",u.style.display="block",setTimeout(()=>{l.style.display="none",u.style.display="none"},1e3);const t=p.elements.search.value.trim();if(!t){c.error({title:"Error",message:"Empty query",messageColor:"#fff"});return}L(t).then(s=>{if(s.hits.length===0)throw i.innerHTML="",new Error("Sorry, there are no images matching your search query. Please try again!");const o=g(s.hits);i.innerHTML=o,S.refresh(),c.success({title:"Success",message:"Images loaded successfully",messageColor:"#fff"})}).catch(s=>{c.error({title:"Error",message:s.message,backgroundColor:"#EF4040",iconColor:"#ffffff",messageColor:"#fff"})})};p.addEventListener("submit",$);
//# sourceMappingURL=commonHelpers.js.map
