import{a as _,S as L,i as c}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function b(a){return a.map(({id:o,webformatURL:s,largeImageURL:t,views:e,likes:r,comments:n,downloads:g,tags:h})=>`
      <a href="${t}" class="card">
         <img class="card__img" src="${s}" alt="${h}"/>
         <div class="card__info">
           <p class="card__numbers"><span>Views:</span> ${e}</p>
           <p class="card__numbers"><span>Likes:</span> ${r}</p>
           <p class="card__numbers"><span>Comments:</span> ${n}</p>
           <p class="card__numbers"><span>Downloads:</span> ${g}</p>
         </div>
      </a>
      `).join("")}const S="https://pixabay.com",w="/api/",E="15968525-5a53092c6d62a7b9e458a529a";async function P(a,o=1,s=18){const t={Accept:"application/json","Content-Type":"application/json"},e=`${S}${w}`;try{return(await _.get(e,{params:{key:E,image_type:"photo",safesearch:!0,orientation:"horizontal",q:a,page:o,per_page:s},headers:{...t}})).data}catch(r){r.response?iziToast.error({title:"Error",message:`HTTP error! status: ${r.response.status} - ${r.response.statusText}`}):iziToast.error({title:"Error",message:r.message});return}}const f=document.querySelector(".form"),u=document.querySelector(".gallery"),T=new L(".gallery a"),l=document.querySelector(".loader"),d=document.querySelector(".loader__overlay"),m=document.querySelector(".js-load-more");let i=1;const p=18;function $(){const a=u.querySelectorAll("img"),o=Array.from(a).map(s=>new Promise((t,e)=>{s.complete?t():(s.onload=t,s.onerror=e)}));return Promise.all(o)}async function y(a){a.preventDefault(),a.target.classList.contains("form")&&(u.innerHTML="",i=1,l.style.display="block",d.style.display="block");const o=f.elements.search.value.trim();if(!o){c.error({title:"Error",message:"Empty query",messageColor:"#fff"}),l.style.display="none",d.style.display="none";return}await P(o,i,p).then(async s=>{const t=s.totalHits;if(s.hits.length===0)throw u.innerHTML="",m.classList.add("load-more-hidden"),l.style.display="none",d.style.display="none",new Error("Sorry, there are no images matching your search query. Please try again!");const e=b(s.hits);if(u.insertAdjacentHTML("beforeend",e),T.refresh(),await $(),c.success({title:"Success",message:"Images loaded successfully",messageColor:"#fff"}),l.style.display="none",d.style.display="none",i*p>=t&&(c.success({title:"Warning",message:"We're sorry, but you've reached the end of search results.",messageColor:"red"}),m.classList.add("load-more-hidden")),i===1&&t>p&&m.classList.remove("load-more-hidden"),a.target.classList.contains("form"))return;let r=document.querySelector(".card__img");window.scrollBy({top:r.height*2+48,left:0,behavior:"smooth"})}).catch(s=>{c.error({title:"Error",message:s.message,backgroundColor:"#EF4040",iconColor:"#ffffff",messageColor:"#fff"})}).finally(s=>{i++})}f.addEventListener("submit",y);m.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
