import{a as _,S as b,i}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function L(a){return a.map(({id:t,webformatURL:s,largeImageURL:o,views:e,likes:r,comments:n,downloads:g,tags:h})=>`
      <a href="${o}" class="card">
         <img class="card__img" src="${s}" alt="${h}" loading="lazy"/>
         <div class="card__info">
           <p class="card__numbers"><span>Views:</span> ${e}</p>
           <p class="card__numbers"><span>Likes:</span> ${r}</p>
           <p class="card__numbers"><span>Comments:</span> ${n}</p>
           <p class="card__numbers"><span>Downloads:</span> ${g}</p>
         </div>
      </a>
      `).join("")}const E="https://pixabay.com",S="/api/",T="15968525-5a53092c6d62a7b9e458a529a";async function $(a,t=1,s=18){const o={Accept:"application/json","Content-Type":"application/json"},e=`${E}${S}`;try{return(await _.get(e,{params:{key:T,image_type:"photo",safesearch:!0,orientation:"horizontal",q:a,page:t,per_page:s},headers:{...o}})).data}catch(r){r.response?iziToast.error({title:"Error",message:`HTTP error! status: ${r.response.status} - ${r.response.statusText}`}):iziToast.error({title:"Error",message:r.message});return}}const p=document.querySelector(".form"),d=document.querySelector(".gallery"),v=new b(".gallery a"),m=document.querySelector(".loader"),f=document.querySelector(".loader__overlay"),l=document.querySelector(".js-load-more");let c=1;const u=18;async function y(a){a.preventDefault(),a.target.classList.contains("form")&&(d.innerHTML="",c=1,m.style.display="block",f.style.display="block",setTimeout(()=>{m.style.display="none",f.style.display="none"},1e3));const t=p.elements.search.value.trim();if(!t){i.error({title:"Error",message:"Empty query",messageColor:"#fff"});return}await $(t,c,u).then(s=>{const o=s.totalHits;if(s.hits.length===0)throw d.innerHTML="",l.classList.add("load-more-hidden"),new Error("Sorry, there are no images matching your search query. Please try again!");const e=L(s.hits);if(d.insertAdjacentHTML("beforeend",e),v.refresh(),i.success({title:"Success",message:"Images loaded successfully",messageColor:"#fff"}),c*u>=o&&(i.success({title:"Warning",message:"We're sorry, but you've reached the end of search results.",messageColor:"red"}),l.classList.add("load-more-hidden")),c===1&&o>u&&l.classList.remove("load-more-hidden"),a.target.classList.contains("form"))return;let r=document.querySelector(".card__img");setTimeout(()=>{window.scrollBy({top:r.height*2+48,left:0,behavior:"smooth"})},1e3)}).catch(s=>{i.error({title:"Error",message:s.message,backgroundColor:"#EF4040",iconColor:"#ffffff",messageColor:"#fff"})}).finally(s=>{c++})}p.addEventListener("submit",y);l.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
